#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="G:\\JOBMART\\JOBMART\\JOBMART\\APP_DATA\\DATABASEJM.MDF")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertloginData(loginData instance);
  partial void UpdateloginData(loginData instance);
  partial void DeleteloginData(loginData instance);
  partial void InsertuserData(userData instance);
  partial void UpdateuserData(userData instance);
  partial void DeleteuserData(userData instance);
  partial void InsertcompanyDataTbl(companyDataTbl instance);
  partial void UpdatecompanyDataTbl(companyDataTbl instance);
  partial void DeletecompanyDataTbl(companyDataTbl instance);
  partial void InsertcompanyPostRef(companyPostRef instance);
  partial void UpdatecompanyPostRef(companyPostRef instance);
  partial void DeletecompanyPostRef(companyPostRef instance);
  partial void InsertjobPostTbl(jobPostTbl instance);
  partial void UpdatejobPostTbl(jobPostTbl instance);
  partial void DeletejobPostTbl(jobPostTbl instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["G__JOBMART_JOBMART_JOBMART_APP_DATA_DATABASEJM_MDFConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<loginData> loginDatas
	{
		get
		{
			return this.GetTable<loginData>();
		}
	}
	
	public System.Data.Linq.Table<userData> userDatas
	{
		get
		{
			return this.GetTable<userData>();
		}
	}
	
	public System.Data.Linq.Table<companyDataTbl> companyDataTbls
	{
		get
		{
			return this.GetTable<companyDataTbl>();
		}
	}
	
	public System.Data.Linq.Table<companyPostRef> companyPostRefs
	{
		get
		{
			return this.GetTable<companyPostRef>();
		}
	}
	
	public System.Data.Linq.Table<jobPostTbl> jobPostTbls
	{
		get
		{
			return this.GetTable<jobPostTbl>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loginData")]
public partial class loginData : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _idNo;
	
	private string _userMail;
	
	private string _userPassword;
	
	private string _usertype;
	
	private string _activity;
	
	private System.Nullable<System.DateTime> _reg_date;
	
	private EntityRef<userData> _userData;
	
	private EntityRef<companyDataTbl> _companyDataTbl;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidNoChanging(string value);
    partial void OnidNoChanged();
    partial void OnuserMailChanging(string value);
    partial void OnuserMailChanged();
    partial void OnuserPasswordChanging(string value);
    partial void OnuserPasswordChanged();
    partial void OnusertypeChanging(string value);
    partial void OnusertypeChanged();
    partial void OnactivityChanging(string value);
    partial void OnactivityChanged();
    partial void Onreg_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onreg_dateChanged();
    #endregion
	
	public loginData()
	{
		this._userData = default(EntityRef<userData>);
		this._companyDataTbl = default(EntityRef<companyDataTbl>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idNo", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string idNo
	{
		get
		{
			return this._idNo;
		}
		set
		{
			if ((this._idNo != value))
			{
				this.OnidNoChanging(value);
				this.SendPropertyChanging();
				this._idNo = value;
				this.SendPropertyChanged("idNo");
				this.OnidNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userMail", DbType="VarChar(50)")]
	public string userMail
	{
		get
		{
			return this._userMail;
		}
		set
		{
			if ((this._userMail != value))
			{
				this.OnuserMailChanging(value);
				this.SendPropertyChanging();
				this._userMail = value;
				this.SendPropertyChanged("userMail");
				this.OnuserMailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userPassword", DbType="VarChar(36)")]
	public string userPassword
	{
		get
		{
			return this._userPassword;
		}
		set
		{
			if ((this._userPassword != value))
			{
				this.OnuserPasswordChanging(value);
				this.SendPropertyChanging();
				this._userPassword = value;
				this.SendPropertyChanged("userPassword");
				this.OnuserPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usertype", DbType="VarChar(15)")]
	public string usertype
	{
		get
		{
			return this._usertype;
		}
		set
		{
			if ((this._usertype != value))
			{
				this.OnusertypeChanging(value);
				this.SendPropertyChanging();
				this._usertype = value;
				this.SendPropertyChanged("usertype");
				this.OnusertypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activity", DbType="VarChar(2)")]
	public string activity
	{
		get
		{
			return this._activity;
		}
		set
		{
			if ((this._activity != value))
			{
				this.OnactivityChanging(value);
				this.SendPropertyChanging();
				this._activity = value;
				this.SendPropertyChanged("activity");
				this.OnactivityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reg_date", DbType="Date")]
	public System.Nullable<System.DateTime> reg_date
	{
		get
		{
			return this._reg_date;
		}
		set
		{
			if ((this._reg_date != value))
			{
				this.Onreg_dateChanging(value);
				this.SendPropertyChanging();
				this._reg_date = value;
				this.SendPropertyChanged("reg_date");
				this.Onreg_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loginData_userData", Storage="_userData", ThisKey="idNo", OtherKey="userId", IsUnique=true, IsForeignKey=false)]
	public userData userData
	{
		get
		{
			return this._userData.Entity;
		}
		set
		{
			userData previousValue = this._userData.Entity;
			if (((previousValue != value) 
						|| (this._userData.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._userData.Entity = null;
					previousValue.loginData = null;
				}
				this._userData.Entity = value;
				if ((value != null))
				{
					value.loginData = this;
				}
				this.SendPropertyChanged("userData");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loginData_companyDataTbl", Storage="_companyDataTbl", ThisKey="idNo", OtherKey="companyId", IsUnique=true, IsForeignKey=false)]
	public companyDataTbl companyDataTbl
	{
		get
		{
			return this._companyDataTbl.Entity;
		}
		set
		{
			companyDataTbl previousValue = this._companyDataTbl.Entity;
			if (((previousValue != value) 
						|| (this._companyDataTbl.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._companyDataTbl.Entity = null;
					previousValue.loginData = null;
				}
				this._companyDataTbl.Entity = value;
				if ((value != null))
				{
					value.loginData = this;
				}
				this.SendPropertyChanged("companyDataTbl");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userData")]
public partial class userData : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _fullName;
	
	private string _userId;
	
	private string _addressOfUser;
	
	private System.Nullable<System.DateTime> _dob;
	
	private string _gender;
	
	private string _division;
	
	private string _contactNo;
	
	private string _degree;
	
	private string _institute;
	
	private string _subjectGrad;
	
	private EntityRef<loginData> _loginData;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfullNameChanging(string value);
    partial void OnfullNameChanged();
    partial void OnuserIdChanging(string value);
    partial void OnuserIdChanged();
    partial void OnaddressOfUserChanging(string value);
    partial void OnaddressOfUserChanged();
    partial void OndobChanging(System.Nullable<System.DateTime> value);
    partial void OndobChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OndivisionChanging(string value);
    partial void OndivisionChanged();
    partial void OncontactNoChanging(string value);
    partial void OncontactNoChanged();
    partial void OndegreeChanging(string value);
    partial void OndegreeChanged();
    partial void OninstituteChanging(string value);
    partial void OninstituteChanged();
    partial void OnsubjectGradChanging(string value);
    partial void OnsubjectGradChanged();
    #endregion
	
	public userData()
	{
		this._loginData = default(EntityRef<loginData>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullName", DbType="VarChar(32)")]
	public string fullName
	{
		get
		{
			return this._fullName;
		}
		set
		{
			if ((this._fullName != value))
			{
				this.OnfullNameChanging(value);
				this.SendPropertyChanging();
				this._fullName = value;
				this.SendPropertyChanged("fullName");
				this.OnfullNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userId", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string userId
	{
		get
		{
			return this._userId;
		}
		set
		{
			if ((this._userId != value))
			{
				if (this._loginData.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnuserIdChanging(value);
				this.SendPropertyChanging();
				this._userId = value;
				this.SendPropertyChanged("userId");
				this.OnuserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addressOfUser", DbType="VarChar(50)")]
	public string addressOfUser
	{
		get
		{
			return this._addressOfUser;
		}
		set
		{
			if ((this._addressOfUser != value))
			{
				this.OnaddressOfUserChanging(value);
				this.SendPropertyChanging();
				this._addressOfUser = value;
				this.SendPropertyChanged("addressOfUser");
				this.OnaddressOfUserChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dob", DbType="Date")]
	public System.Nullable<System.DateTime> dob
	{
		get
		{
			return this._dob;
		}
		set
		{
			if ((this._dob != value))
			{
				this.OndobChanging(value);
				this.SendPropertyChanging();
				this._dob = value;
				this.SendPropertyChanged("dob");
				this.OndobChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(10)")]
	public string gender
	{
		get
		{
			return this._gender;
		}
		set
		{
			if ((this._gender != value))
			{
				this.OngenderChanging(value);
				this.SendPropertyChanging();
				this._gender = value;
				this.SendPropertyChanged("gender");
				this.OngenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_division", DbType="VarChar(15)")]
	public string division
	{
		get
		{
			return this._division;
		}
		set
		{
			if ((this._division != value))
			{
				this.OndivisionChanging(value);
				this.SendPropertyChanging();
				this._division = value;
				this.SendPropertyChanged("division");
				this.OndivisionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactNo", DbType="VarChar(12)")]
	public string contactNo
	{
		get
		{
			return this._contactNo;
		}
		set
		{
			if ((this._contactNo != value))
			{
				this.OncontactNoChanging(value);
				this.SendPropertyChanging();
				this._contactNo = value;
				this.SendPropertyChanged("contactNo");
				this.OncontactNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_degree", DbType="VarChar(10)")]
	public string degree
	{
		get
		{
			return this._degree;
		}
		set
		{
			if ((this._degree != value))
			{
				this.OndegreeChanging(value);
				this.SendPropertyChanging();
				this._degree = value;
				this.SendPropertyChanged("degree");
				this.OndegreeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_institute", DbType="VarChar(50)")]
	public string institute
	{
		get
		{
			return this._institute;
		}
		set
		{
			if ((this._institute != value))
			{
				this.OninstituteChanging(value);
				this.SendPropertyChanging();
				this._institute = value;
				this.SendPropertyChanged("institute");
				this.OninstituteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subjectGrad", DbType="VarChar(10)")]
	public string subjectGrad
	{
		get
		{
			return this._subjectGrad;
		}
		set
		{
			if ((this._subjectGrad != value))
			{
				this.OnsubjectGradChanging(value);
				this.SendPropertyChanging();
				this._subjectGrad = value;
				this.SendPropertyChanged("subjectGrad");
				this.OnsubjectGradChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loginData_userData", Storage="_loginData", ThisKey="userId", OtherKey="idNo", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public loginData loginData
	{
		get
		{
			return this._loginData.Entity;
		}
		set
		{
			loginData previousValue = this._loginData.Entity;
			if (((previousValue != value) 
						|| (this._loginData.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._loginData.Entity = null;
					previousValue.userData = null;
				}
				this._loginData.Entity = value;
				if ((value != null))
				{
					value.userData = this;
					this._userId = value.idNo;
				}
				else
				{
					this._userId = default(string);
				}
				this.SendPropertyChanged("loginData");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.companyDataTbl")]
public partial class companyDataTbl : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _companyId;
	
	private string _companyName;
	
	private string _companyAddress;
	
	private string _companyWebSite;
	
	private System.Nullable<System.DateTime> _foundationOn;
	
	private string _headQuater;
	
	private string _contactNo;
	
	private EntitySet<companyPostRef> _companyPostRefs;
	
	private EntityRef<loginData> _loginData;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncompanyIdChanging(string value);
    partial void OncompanyIdChanged();
    partial void OncompanyNameChanging(string value);
    partial void OncompanyNameChanged();
    partial void OncompanyAddressChanging(string value);
    partial void OncompanyAddressChanged();
    partial void OncompanyWebSiteChanging(string value);
    partial void OncompanyWebSiteChanged();
    partial void OnfoundationOnChanging(System.Nullable<System.DateTime> value);
    partial void OnfoundationOnChanged();
    partial void OnheadQuaterChanging(string value);
    partial void OnheadQuaterChanged();
    partial void OncontactNoChanging(string value);
    partial void OncontactNoChanged();
    #endregion
	
	public companyDataTbl()
	{
		this._companyPostRefs = new EntitySet<companyPostRef>(new Action<companyPostRef>(this.attach_companyPostRefs), new Action<companyPostRef>(this.detach_companyPostRefs));
		this._loginData = default(EntityRef<loginData>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyId", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string companyId
	{
		get
		{
			return this._companyId;
		}
		set
		{
			if ((this._companyId != value))
			{
				if (this._loginData.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OncompanyIdChanging(value);
				this.SendPropertyChanging();
				this._companyId = value;
				this.SendPropertyChanged("companyId");
				this.OncompanyIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyName", DbType="VarChar(32)")]
	public string companyName
	{
		get
		{
			return this._companyName;
		}
		set
		{
			if ((this._companyName != value))
			{
				this.OncompanyNameChanging(value);
				this.SendPropertyChanging();
				this._companyName = value;
				this.SendPropertyChanged("companyName");
				this.OncompanyNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyAddress", DbType="VarChar(50)")]
	public string companyAddress
	{
		get
		{
			return this._companyAddress;
		}
		set
		{
			if ((this._companyAddress != value))
			{
				this.OncompanyAddressChanging(value);
				this.SendPropertyChanging();
				this._companyAddress = value;
				this.SendPropertyChanged("companyAddress");
				this.OncompanyAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyWebSite", DbType="VarChar(50)")]
	public string companyWebSite
	{
		get
		{
			return this._companyWebSite;
		}
		set
		{
			if ((this._companyWebSite != value))
			{
				this.OncompanyWebSiteChanging(value);
				this.SendPropertyChanging();
				this._companyWebSite = value;
				this.SendPropertyChanged("companyWebSite");
				this.OncompanyWebSiteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foundationOn", DbType="Date")]
	public System.Nullable<System.DateTime> foundationOn
	{
		get
		{
			return this._foundationOn;
		}
		set
		{
			if ((this._foundationOn != value))
			{
				this.OnfoundationOnChanging(value);
				this.SendPropertyChanging();
				this._foundationOn = value;
				this.SendPropertyChanged("foundationOn");
				this.OnfoundationOnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_headQuater", DbType="VarChar(15)")]
	public string headQuater
	{
		get
		{
			return this._headQuater;
		}
		set
		{
			if ((this._headQuater != value))
			{
				this.OnheadQuaterChanging(value);
				this.SendPropertyChanging();
				this._headQuater = value;
				this.SendPropertyChanged("headQuater");
				this.OnheadQuaterChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactNo", DbType="VarChar(12)")]
	public string contactNo
	{
		get
		{
			return this._contactNo;
		}
		set
		{
			if ((this._contactNo != value))
			{
				this.OncontactNoChanging(value);
				this.SendPropertyChanging();
				this._contactNo = value;
				this.SendPropertyChanged("contactNo");
				this.OncontactNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="companyDataTbl_companyPostRef", Storage="_companyPostRefs", ThisKey="companyId", OtherKey="companyId")]
	public EntitySet<companyPostRef> companyPostRefs
	{
		get
		{
			return this._companyPostRefs;
		}
		set
		{
			this._companyPostRefs.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loginData_companyDataTbl", Storage="_loginData", ThisKey="companyId", OtherKey="idNo", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public loginData loginData
	{
		get
		{
			return this._loginData.Entity;
		}
		set
		{
			loginData previousValue = this._loginData.Entity;
			if (((previousValue != value) 
						|| (this._loginData.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._loginData.Entity = null;
					previousValue.companyDataTbl = null;
				}
				this._loginData.Entity = value;
				if ((value != null))
				{
					value.companyDataTbl = this;
					this._companyId = value.idNo;
				}
				else
				{
					this._companyId = default(string);
				}
				this.SendPropertyChanged("loginData");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_companyPostRefs(companyPostRef entity)
	{
		this.SendPropertyChanging();
		entity.companyDataTbl = this;
	}
	
	private void detach_companyPostRefs(companyPostRef entity)
	{
		this.SendPropertyChanging();
		entity.companyDataTbl = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.companyPostRef")]
public partial class companyPostRef : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _postId;
	
	private string _companyId;
	
	private System.Nullable<System.DateTime> _postingTime;
	
	private string _activity;
	
	private EntityRef<jobPostTbl> _jobPostTbl;
	
	private EntityRef<companyDataTbl> _companyDataTbl;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpostIdChanging(string value);
    partial void OnpostIdChanged();
    partial void OncompanyIdChanging(string value);
    partial void OncompanyIdChanged();
    partial void OnpostingTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnpostingTimeChanged();
    partial void OnactivityChanging(string value);
    partial void OnactivityChanged();
    #endregion
	
	public companyPostRef()
	{
		this._jobPostTbl = default(EntityRef<jobPostTbl>);
		this._companyDataTbl = default(EntityRef<companyDataTbl>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postId", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string postId
	{
		get
		{
			return this._postId;
		}
		set
		{
			if ((this._postId != value))
			{
				this.OnpostIdChanging(value);
				this.SendPropertyChanging();
				this._postId = value;
				this.SendPropertyChanged("postId");
				this.OnpostIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyId", DbType="VarChar(20)")]
	public string companyId
	{
		get
		{
			return this._companyId;
		}
		set
		{
			if ((this._companyId != value))
			{
				if (this._companyDataTbl.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OncompanyIdChanging(value);
				this.SendPropertyChanging();
				this._companyId = value;
				this.SendPropertyChanged("companyId");
				this.OncompanyIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postingTime", DbType="Date")]
	public System.Nullable<System.DateTime> postingTime
	{
		get
		{
			return this._postingTime;
		}
		set
		{
			if ((this._postingTime != value))
			{
				this.OnpostingTimeChanging(value);
				this.SendPropertyChanging();
				this._postingTime = value;
				this.SendPropertyChanged("postingTime");
				this.OnpostingTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activity", DbType="VarChar(2)")]
	public string activity
	{
		get
		{
			return this._activity;
		}
		set
		{
			if ((this._activity != value))
			{
				this.OnactivityChanging(value);
				this.SendPropertyChanging();
				this._activity = value;
				this.SendPropertyChanged("activity");
				this.OnactivityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="companyPostRef_jobPostTbl", Storage="_jobPostTbl", ThisKey="postId", OtherKey="postId", IsUnique=true, IsForeignKey=false)]
	public jobPostTbl jobPostTbl
	{
		get
		{
			return this._jobPostTbl.Entity;
		}
		set
		{
			jobPostTbl previousValue = this._jobPostTbl.Entity;
			if (((previousValue != value) 
						|| (this._jobPostTbl.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._jobPostTbl.Entity = null;
					previousValue.companyPostRef = null;
				}
				this._jobPostTbl.Entity = value;
				if ((value != null))
				{
					value.companyPostRef = this;
				}
				this.SendPropertyChanged("jobPostTbl");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="companyDataTbl_companyPostRef", Storage="_companyDataTbl", ThisKey="companyId", OtherKey="companyId", IsForeignKey=true)]
	public companyDataTbl companyDataTbl
	{
		get
		{
			return this._companyDataTbl.Entity;
		}
		set
		{
			companyDataTbl previousValue = this._companyDataTbl.Entity;
			if (((previousValue != value) 
						|| (this._companyDataTbl.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._companyDataTbl.Entity = null;
					previousValue.companyPostRefs.Remove(this);
				}
				this._companyDataTbl.Entity = value;
				if ((value != null))
				{
					value.companyPostRefs.Add(this);
					this._companyId = value.companyId;
				}
				else
				{
					this._companyId = default(string);
				}
				this.SendPropertyChanged("companyDataTbl");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.jobPostTbl")]
public partial class jobPostTbl : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _postId;
	
	private string _jobTitle;
	
	private string _positionName;
	
	private System.Nullable<System.DateTime> _deadLine;
	
	private System.Nullable<int> _noOfVacancy;
	
	private string _jobDescription;
	
	private string _jobNature;
	
	private string _jobRequirment;
	
	private string _salaryOthers;
	
	private string _jobLocation;
	
	private EntityRef<companyPostRef> _companyPostRef;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpostIdChanging(string value);
    partial void OnpostIdChanged();
    partial void OnjobTitleChanging(string value);
    partial void OnjobTitleChanged();
    partial void OnpositionNameChanging(string value);
    partial void OnpositionNameChanged();
    partial void OndeadLineChanging(System.Nullable<System.DateTime> value);
    partial void OndeadLineChanged();
    partial void OnnoOfVacancyChanging(System.Nullable<int> value);
    partial void OnnoOfVacancyChanged();
    partial void OnjobDescriptionChanging(string value);
    partial void OnjobDescriptionChanged();
    partial void OnjobNatureChanging(string value);
    partial void OnjobNatureChanged();
    partial void OnjobRequirmentChanging(string value);
    partial void OnjobRequirmentChanged();
    partial void OnsalaryOthersChanging(string value);
    partial void OnsalaryOthersChanged();
    partial void OnjobLocationChanging(string value);
    partial void OnjobLocationChanged();
    #endregion
	
	public jobPostTbl()
	{
		this._companyPostRef = default(EntityRef<companyPostRef>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postId", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string postId
	{
		get
		{
			return this._postId;
		}
		set
		{
			if ((this._postId != value))
			{
				if (this._companyPostRef.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnpostIdChanging(value);
				this.SendPropertyChanging();
				this._postId = value;
				this.SendPropertyChanged("postId");
				this.OnpostIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobTitle", DbType="VarChar(70)")]
	public string jobTitle
	{
		get
		{
			return this._jobTitle;
		}
		set
		{
			if ((this._jobTitle != value))
			{
				this.OnjobTitleChanging(value);
				this.SendPropertyChanging();
				this._jobTitle = value;
				this.SendPropertyChanged("jobTitle");
				this.OnjobTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_positionName", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string positionName
	{
		get
		{
			return this._positionName;
		}
		set
		{
			if ((this._positionName != value))
			{
				this.OnpositionNameChanging(value);
				this.SendPropertyChanging();
				this._positionName = value;
				this.SendPropertyChanged("positionName");
				this.OnpositionNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deadLine", DbType="Date")]
	public System.Nullable<System.DateTime> deadLine
	{
		get
		{
			return this._deadLine;
		}
		set
		{
			if ((this._deadLine != value))
			{
				this.OndeadLineChanging(value);
				this.SendPropertyChanging();
				this._deadLine = value;
				this.SendPropertyChanged("deadLine");
				this.OndeadLineChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noOfVacancy", DbType="Int")]
	public System.Nullable<int> noOfVacancy
	{
		get
		{
			return this._noOfVacancy;
		}
		set
		{
			if ((this._noOfVacancy != value))
			{
				this.OnnoOfVacancyChanging(value);
				this.SendPropertyChanging();
				this._noOfVacancy = value;
				this.SendPropertyChanged("noOfVacancy");
				this.OnnoOfVacancyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobDescription", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string jobDescription
	{
		get
		{
			return this._jobDescription;
		}
		set
		{
			if ((this._jobDescription != value))
			{
				this.OnjobDescriptionChanging(value);
				this.SendPropertyChanging();
				this._jobDescription = value;
				this.SendPropertyChanged("jobDescription");
				this.OnjobDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobNature", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string jobNature
	{
		get
		{
			return this._jobNature;
		}
		set
		{
			if ((this._jobNature != value))
			{
				this.OnjobNatureChanging(value);
				this.SendPropertyChanging();
				this._jobNature = value;
				this.SendPropertyChanged("jobNature");
				this.OnjobNatureChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobRequirment", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string jobRequirment
	{
		get
		{
			return this._jobRequirment;
		}
		set
		{
			if ((this._jobRequirment != value))
			{
				this.OnjobRequirmentChanging(value);
				this.SendPropertyChanging();
				this._jobRequirment = value;
				this.SendPropertyChanged("jobRequirment");
				this.OnjobRequirmentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salaryOthers", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string salaryOthers
	{
		get
		{
			return this._salaryOthers;
		}
		set
		{
			if ((this._salaryOthers != value))
			{
				this.OnsalaryOthersChanging(value);
				this.SendPropertyChanging();
				this._salaryOthers = value;
				this.SendPropertyChanged("salaryOthers");
				this.OnsalaryOthersChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobLocation", DbType="VarChar(50)")]
	public string jobLocation
	{
		get
		{
			return this._jobLocation;
		}
		set
		{
			if ((this._jobLocation != value))
			{
				this.OnjobLocationChanging(value);
				this.SendPropertyChanging();
				this._jobLocation = value;
				this.SendPropertyChanged("jobLocation");
				this.OnjobLocationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="companyPostRef_jobPostTbl", Storage="_companyPostRef", ThisKey="postId", OtherKey="postId", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
	public companyPostRef companyPostRef
	{
		get
		{
			return this._companyPostRef.Entity;
		}
		set
		{
			companyPostRef previousValue = this._companyPostRef.Entity;
			if (((previousValue != value) 
						|| (this._companyPostRef.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._companyPostRef.Entity = null;
					previousValue.jobPostTbl = null;
				}
				this._companyPostRef.Entity = value;
				if ((value != null))
				{
					value.jobPostTbl = this;
					this._postId = value.postId;
				}
				else
				{
					this._postId = default(string);
				}
				this.SendPropertyChanged("companyPostRef");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
